services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    environment:
      - KC_DB=postgres
      - KC_DB_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8787:8787"
    command:
      - start-dev
      - --features=admin-fine-grained-authz
      - --import-realm
      - --proxy-headers=forwarded
    networks:
      - webapp-network
      - keycloak-network

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "admin"]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    ports:
      - "5432:5432"
    networks:
      - keycloak-network

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      # Auth.js Keycloak env vars
      - AUTH_KEYCLOAK_ID=webapp
      - AUTH_KEYCLOAK_ISSUER=http://localhost:8080/realms/webapp
      - AUTH_KEYCLOAK_SECRET=D7fseyYJ6WqWC3MPPYTTdgIzlE563d0l

      # Auth.js env vars
      - AUTH_SECRET=MohY0/2zSQw/psWEnejC2ka3Al0oifvY4YjOkUaFfnI=
      - AUTH_URL=http://localhost:4321/auth
      - AUTH_KEYCLOAK_DOCKER_URL=http://keycloak:8080/realms/webapp
      - AUTH_REDIRECT_PROXY_URL=http://localhost:4321/auth
      - AUTH_TRUST_HOST=true
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    networks:
      - webapp-network

networks:
  webapp-network:
  keycloak-network:
